/*
 * ASP_NET API
 *
 * ASP_NET API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests : IDisposable
    {
        private DefaultApi instance;

        public DefaultApiTests()
        {
            instance = new DefaultApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DefaultApi
            //Assert.IsType<DefaultApi>(instance);
        }

        /// <summary>
        /// Test ApiMesstationGet
        /// </summary>
        [Fact]
        public void ApiMesstationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiMesstationGet();
        }

        /// <summary>
        /// Test ApiMesstationIdDelete
        /// </summary>
        [Fact]
        public void ApiMesstationIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiMesstationIdDelete(id);
        }

        /// <summary>
        /// Test ApiMesstationIdGet
        /// </summary>
        [Fact]
        public void ApiMesstationIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiMesstationIdGet(id);
        }

        /// <summary>
        /// Test ApiMesstationIdMesswertMesswertIdDelete
        /// </summary>
        [Fact]
        public void ApiMesstationIdMesswertMesswertIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //int messwertId = null;
            //instance.ApiMesstationIdMesswertMesswertIdDelete(id, messwertId);
        }

        /// <summary>
        /// Test ApiMesstationIdMesswertPost
        /// </summary>
        [Fact]
        public void ApiMesstationIdMesswertPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiMesstationIdMesswertPost(id);
        }

        /// <summary>
        /// Test ApiMesstationIdPut
        /// </summary>
        [Fact]
        public void ApiMesstationIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiMesstationIdPut(id);
        }

        /// <summary>
        /// Test ApiMesstationPost
        /// </summary>
        [Fact]
        public void ApiMesstationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiMesstationPost();
        }
    }
}
